version: '3'
services:

    nginx:
      image: nginx:alpine
      build: ./docker/nginx
      container_name: "nginx"
      volumes:
          - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
          - ./laravel:/var/www/html
          - "phpsocket:/var/run"
      ports:
          - "8000:80"
      depends_on:
          - php

    php:
      image: php:fpm-alpine
      build: ./docker/php-fpm
      container_name: "Laravel"
      volumes:
          - ./laravel:/var/www/html
          - ./docker/php-fpm/zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
          - "phpsocket:/var/run"

    composer:
      build: ./docker/composer
      container_name: "composer"
      volumes:
          - ./laravel:/var/www/html

    postgres:
      image: postgres
      container_name: "postgres"
      volumes:
          - ./postgres:/var/lib/postgres
      ports:
          - "5432:5432"
      restart: always
      depends_on:
          - php
      environment:
          - POSTGRES_USER=root
          - POSTGRES_PASSWORD=password
      tty: true

    pgweb:
      image: sosedoff/pgweb
      container_name: "pgweb"
      ports:
          - "8081:8081"
      environment:
          - DATABASE_URL=postgres://root:password@postgres:5432/<DBname>?sslmode=disable
      links:
          - postgres:postgres
      restart: always
      depends_on:
          - postgres
      tty: true

    redis:
      image: redis:4.0.9-alpine
      container_name: "redis"
      volumes:
          - ./redis:/data
      ports:
          - "6379:6379"
      restart: always
      tty: true

    nuxt:
      image: node-express-dev:1.0
      build: ./docker/nuxt
      container_name: "nuxt"
      volumes:
          - ./nuxt:/var/www/html/nuxt
      ports:
        - "3000:3000"
      tty: true

volumes:
    postgres-data:
      driver: local
    pgweb-data:
      driver: local
    phpsocket:
